apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app

  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: ghcr.io/rullabcde/demo/next:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: mysql-secret
---
apiVersion: v1
kind: Service

metadata:
  name: next-app-svc
  namespace: dev

spec:
  selector:
    app: next-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
