apiVersion: apps/v1
kind: Deployment

metadata:
  name: next-app
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app

  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: rullabcd/next:v1.0.0
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: next-secrets
              key: database-url
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: next-config
              key: nextauth-url
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: next-config
              key: node-env
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service

metadata:
  name: next-app-service
  namespace: dev

spec:
  selector:
    app: next-app
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
