apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app

  template:
    metadata:
      labels:
        app: next-app
    spec:
      initContainers:
      - name: wait-migrator
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "Waiting DB Ready..."
          until nc -z mysql 3306; do
            echo "DB belum ready, tunggu 10 detik..."
            sleep 10
          done
          echo "Database ready!"
      containers:
      - name: next-app
        image: ghcr.io/rullabcde/demo/next:4.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: mysql-secret
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
