apiVersion: batch/v1
kind: Job

metadata:
  name: migrator
  namespace: dev

spec:
  template:
    metadata:
      labels:
        app: migrator
    spec:
      restartPolicy: Never
      hostNetwork: true
      containers:
      - name: migrator
        image: rullabcd/next-migrator:v1.0.0
        command: [ "sh", "-c" ]
        args: [ "npx prisma migrate deploy && npx prisma db seed" ]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: next-secrets
              key: database-url
