apiVersion: v1
kind: Secret

metadata:
  name: next-secrets
  namespace: dev

type: Opaque
stringData:
  mysql-root-password: "siswasiswa"
  mysql-password: "rullabcd"
  database-url: "mysql://rullabcd:rullabcd@mysql-service:3306/coba"
  init.sql: |
    CREATE USER IF NOT EXISTS 'rullabcd'@'%' IDENTIFIED BY 'rullabcd';
    GRANT ALL PRIVILEGES ON coba.* TO 'rullabcd'@'%';
    FLUSH PRIVILEGES;
