apiVersion: v1
kind: Service

metadata:
  name: learning-svc
  namespace: education

spec:
  type: NodePort

  selector:
    app: learning
    version: v2
    env: prod

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  - protocol: TCP
    port: 2020
    targetPort: 2020
    nodePort: 30020
