apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: tokokita-prod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service
      tier: backend

  template:
    metadata:
      labels:
        app: user-service
        tier: backend

    spec:
      containers:
      - name: user-app
        image: node:16-alpine
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: tokokita-secret
              key: db.username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: tokokita-secret
              key: db.password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tokokita-secret
              key: jwt.secret
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tokokita-config
              key: database.host
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: tokokita-config
              key: redis.host

      - name: redis-cache
        image: redis:7-alpine
        ports:
        - containerPort: 6379
